# Generated by Django 3.1.1 on 2020-09-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0009_auto_20200905_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
