# Generated by Django 3.1.1 on 2020-09-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0017_auto_20200922_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.ManyToManyField(to='Groups.Mark'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='faculty',
            field=models.CharField(max_length=25),
        ),
    ]
