# Generated by Django 3.1.1 on 2020-09-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0019_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='type',
            field=models.CharField(choices=[('Exam', 'Exam'), ('Test', 'Test')], max_length=10),
        ),
    ]
