# Generated by Django 3.1.1 on 2020-09-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0020_auto_20200927_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
