# Generated by Django 3.1.1 on 2020-09-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0021_group_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
