# Generated by Django 3.1.1 on 2020-10-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0023_auto_20200929_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avg_mark',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
