# Generated by Django 3.1.1 on 2020-10-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0026_auto_20201003_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.ManyToManyField(related_name='marks_set', to='Groups.Mark'),
        ),
    ]
