# Generated by Django 3.1.1 on 2020-10-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0028_auto_20201003_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.ManyToManyField(to='Groups.Mark'),
        ),
    ]
