# Generated by Django 3.1.1 on 2020-10-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0030_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='student',
        ),
    ]
