# Generated by Django 3.1.1 on 2020-10-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0031_remove_profile_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_registered',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
