# Generated by Django 3.1.1 on 2020-10-04 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0033_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Groups.student', unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_registered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
