# Generated by Django 3.1.1 on 2020-10-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0036_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_registered',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
    ]
