# Generated by Django 3.1.1 on 2020-10-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0037_auto_20201007_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
