# Generated by Django 3.1.1 on 2020-10-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0038_student_is_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_lang',
            field=models.CharField(default='C++', max_length=25),
        ),
    ]
